#pragma once

#ifndef _D3DTNL_RENDERER_Z_H_
#define _D3DTNL_RENDERER_Z_H_

#include <d3d9.h>
#include <d3dx9.h>

#include "Renderer_Z.h"

PACK_PUSH
ADDRESSVFTABLE(0x009D71CC, D3D_Renderer_Z);
class __declspec(dllexport) D3D_Renderer_Z : public Renderer_Z
{
public:
    ADDRESSVF(0x008362D0, D3D_Renderer_Z, Renderer_Z_vftable_0);
    virtual void Renderer_Z_vftable_0() override;
    ADDRESSSYMBOL(0x00836EC0, "?Renderer_Z_vftable_2@D3D_Renderer_Z@@UAEXXZ");
    virtual void Renderer_Z_vftable_2() override;
    ADDRESSSYMBOL(0x008521B0, "?Renderer_Z_vftable_4@D3D_Renderer_Z@@UAEXXZ");
    virtual void Renderer_Z_vftable_4() override;
    ADDRESSSYMBOL(0x00858AC0, "?Renderer_Z_vftable_5@D3D_Renderer_Z@@UAEXXZ");
    virtual void Renderer_Z_vftable_5() override;
    ADDRESSVF(0x00858AE0, D3D_Renderer_Z, Renderer_Z_vftable_6);
    virtual void Renderer_Z_vftable_6() override;
    ADDRESSVF(0x00843100, D3D_Renderer_Z, Renderer_Z_vftable_7);
    virtual void Renderer_Z_vftable_7() override;
    ADDRESSVF(0x008430D0, D3D_Renderer_Z, Renderer_Z_vftable_8);
    virtual void Renderer_Z_vftable_8() override;
    ADDRESSSYMBOL(0x00858B30, "?Renderer_Z_vftable_11@D3D_Renderer_Z@@UAEXXZ");
    virtual void Renderer_Z_vftable_11() override;
    ADDRESSVF(0x008385D0, D3D_Renderer_Z, Renderer_Z_vftable_12);
    virtual void Renderer_Z_vftable_12() override;
    ADDRESSSYMBOL(0x0084FC80, "?Renderer_Z_vftable_14@D3D_Renderer_Z@@UAEXH@Z");
    virtual void Renderer_Z_vftable_14(int) override;
    ADDRESSVF(0x00843840, D3D_Renderer_Z, Renderer_Z_vftable_16);
    virtual void Renderer_Z_vftable_16() override;
    ADDRESSSYMBOL(0x00843890, "?Renderer_Z_vftable_17@D3D_Renderer_Z@@UAEDHHHHHH@Z");
    virtual char Renderer_Z_vftable_17(int, int, int, int, int, int) override;
    ADDRESSSYMBOL(0x00843A00, "?Renderer_Z_vftable_18@D3D_Renderer_Z@@UAEXHHH@Z");
    virtual void Renderer_Z_vftable_18(int, int, int) override;
    ADDRESSSYMBOL(0x00839CD0, "?Renderer_Z_vftable_19@D3D_Renderer_Z@@UAEXH@Z");
    virtual void Renderer_Z_vftable_19(int) override;
    ADDRESSSYMBOL(0x00839CA0, "?Renderer_Z_vftable_20@D3D_Renderer_Z@@UAEXH@Z");
    virtual void Renderer_Z_vftable_20(int) override;
    ADDRESSSYMBOL(0x00839C70, "?Renderer_Z_vftable_21@D3D_Renderer_Z@@UAEXH@Z");
    virtual void Renderer_Z_vftable_21(int) override;
    ADDRESSVF(0x00839C60, D3D_Renderer_Z, Renderer_Z_vftable_23);
    virtual void Renderer_Z_vftable_23() override;
    ADDRESSVF(0x00839C50, D3D_Renderer_Z, Renderer_Z_vftable_24);
    virtual void Renderer_Z_vftable_24() override;
    ADDRESSVF(0x00839C40, D3D_Renderer_Z, Renderer_Z_vftable_25);
    virtual void Renderer_Z_vftable_25() override;
    ADDRESSVF(0x0084F5A0, D3D_Renderer_Z, Renderer_Z_vftable_29);
    virtual void Renderer_Z_vftable_29() override;
    ADDRESSSYMBOL(0x0084F750, "?Renderer_Z_vftable_30@D3D_Renderer_Z@@UAEXXZ");
    virtual void Renderer_Z_vftable_30() override;
    ADDRESSSYMBOL(0x0084F580, "?Renderer_Z_vftable_31@D3D_Renderer_Z@@UAEHXZ");
    virtual int Renderer_Z_vftable_31() override;
    ADDRESSSYMBOL(0x0084FB60, "?Renderer_Z_vftable_32@D3D_Renderer_Z@@UAEXHHHHHHHH@Z");
    virtual void Renderer_Z_vftable_32(int, int, int, int, int, int, int, int) override;
    ADDRESSSYMBOL(0x0084F980, "?Renderer_Z_vftable_33@D3D_Renderer_Z@@UAEXH@Z");
    virtual void Renderer_Z_vftable_33(int) override;
    ADDRESSSYMBOL(0x0084FA20, "?Renderer_Z_vftable_34@D3D_Renderer_Z@@UAEXH@Z");
    virtual void Renderer_Z_vftable_34(int) override;
    ADDRESSSYMBOL(0x0084F9A0, "?Renderer_Z_vftable_35@D3D_Renderer_Z@@UAEXHH@Z");
    virtual void Renderer_Z_vftable_35(int, int) override;
    ADDRESSSYMBOL(0x0084FAD0, "?Renderer_Z_vftable_36@D3D_Renderer_Z@@UAEXHH@Z");
    virtual void Renderer_Z_vftable_36(int, int) override;
    ADDRESSSYMBOL(0x00839C20, "?Renderer_Z_vftable_37@D3D_Renderer_Z@@UAEXH@Z");
    virtual void Renderer_Z_vftable_37(int) override;
    ADDRESSSYMBOL(0x0084EC10, "?Renderer_Z_vftable_38@D3D_Renderer_Z@@UAEXH@Z");
    virtual void Renderer_Z_vftable_38(int) override;
    ADDRESSSYMBOL(0x0084F1C0, "?Renderer_Z_vftable_39@D3D_Renderer_Z@@UAEXH@Z");
    virtual void Renderer_Z_vftable_39(int) override;
    ADDRESSVF(0x00839BD0, D3D_Renderer_Z, Renderer_Z_vftable_40);
    virtual void Renderer_Z_vftable_40() override;
    virtual void Renderer_Z_vftable_41(int, int) override;
    ADDRESSSYMBOL(0x00856230, "?Renderer_Z_vftable_42@D3D_Renderer_Z@@UAEXH@Z");
    virtual void Renderer_Z_vftable_42(int) override;
    ADDRESSVF(0x0084F470, D3D_Renderer_Z, Renderer_Z_vftable_43);
    virtual void Renderer_Z_vftable_43() override;
    ADDRESSSYMBOL(0x00837660, "?Renderer_Z_vftable_46@D3D_Renderer_Z@@UAEHH@Z");
    virtual int Renderer_Z_vftable_46(int) override;
    ADDRESSSYMBOL(0x00837830, "?Renderer_Z_vftable_47@D3D_Renderer_Z@@UAEHH@Z");
    virtual int Renderer_Z_vftable_47(int) override;
    ADDRESSSYMBOL(0x00837800, "?Renderer_Z_vftable_48@D3D_Renderer_Z@@UAEHH@Z");
    virtual int Renderer_Z_vftable_48(int) override;
    ADDRESSSYMBOL(0x00837940, "?Renderer_Z_vftable_49@D3D_Renderer_Z@@UAEHH@Z");
    virtual int Renderer_Z_vftable_49(int) override;
    ADDRESSSYMBOL(0x00837950, "?Renderer_Z_vftable_50@D3D_Renderer_Z@@UAEHH@Z");
    virtual int Renderer_Z_vftable_50(int) override;
    ADDRESSSYMBOL(0x00837A40, "?Renderer_Z_vftable_51@D3D_Renderer_Z@@UAEHH@Z");
    virtual int Renderer_Z_vftable_51(int) override;
    ADDRESSSYMBOL(0x00837A80, "?Renderer_Z_vftable_52@D3D_Renderer_Z@@UAEHXZ");
    virtual int Renderer_Z_vftable_52() override;
    ADDRESSSYMBOL(0x00837AC0, "?Renderer_Z_vftable_53@D3D_Renderer_Z@@UAEHXZ");
    virtual int Renderer_Z_vftable_53() override;
    ADDRESSSYMBOL(0x00837CE0, "?Renderer_Z_vftable_54@D3D_Renderer_Z@@UAEHXZ");
    virtual int Renderer_Z_vftable_54() override;
    ADDRESSSYMBOL(0x00837C80, "?Renderer_Z_vftable_55@D3D_Renderer_Z@@UAEHXZ");
    virtual int Renderer_Z_vftable_55() override;
    ADDRESSSYMBOL(0x00837FE0, "?Renderer_Z_vftable_56@D3D_Renderer_Z@@UAEHXZ");
    virtual int Renderer_Z_vftable_56() override;
    ADDRESSSYMBOL(0x00837C50, "?Renderer_Z_vftable_57@D3D_Renderer_Z@@UAEHXZ");
    virtual int Renderer_Z_vftable_57() override;
    ADDRESSSYMBOL(0x00837E60, "?Renderer_Z_vftable_58@D3D_Renderer_Z@@UAEHXZ");
    virtual int Renderer_Z_vftable_58() override;
    ADDRESSSYMBOL(0x00837CB0, "?Renderer_Z_vftable_59@D3D_Renderer_Z@@UAEHXZ");
    virtual int Renderer_Z_vftable_59() override;
    ADDRESSSYMBOL(0x0084D250, "?Renderer_Z_vftable_61@D3D_Renderer_Z@@UAEXH@Z");
    virtual void Renderer_Z_vftable_61(int) override;
    ADDRESSVF(0x0084C1D0, D3D_Renderer_Z, Renderer_Z_vftable_64);
    virtual void Renderer_Z_vftable_64() override;
    ADDRESSVF(0x0084C270, D3D_Renderer_Z, Renderer_Z_vftable_65);
    virtual void Renderer_Z_vftable_65() override;
    ADDRESSVF(0x0084C250, D3D_Renderer_Z, Renderer_Z_vftable_66);
    virtual void Renderer_Z_vftable_66() override;
    ADDRESSVF(0x0084C2F0, D3D_Renderer_Z, Renderer_Z_vftable_67);
    virtual void Renderer_Z_vftable_67() override;
    ADDRESSVF(0x0086C990, D3D_Renderer_Z, Renderer_Z_vftable_68);
    virtual void Renderer_Z_vftable_68() override;
    ADDRESSSYMBOL(0x0086C840, "?Renderer_Z_vftable_70@D3D_Renderer_Z@@UAEDH@Z");
    virtual char Renderer_Z_vftable_70(int) override;
    virtual int Renderer_Z_vftable_75() override;
    ADDRESSVF(0x0086FE70, D3D_Renderer_Z, Renderer_Z_vftable_76);
    virtual void Renderer_Z_vftable_76() override;
    ADDRESSVF(0x00836F80, D3D_Renderer_Z, Renderer_Z_vftable_77);
    virtual void Renderer_Z_vftable_77() override;
    ADDRESSSYMBOL(0x00850090, "?Renderer_Z_vftable_81@D3D_Renderer_Z@@UAEHHHHH@Z");
    virtual int Renderer_Z_vftable_81(int, int, int, int) override;
    ADDRESSSYMBOL(0x008500C0, "?Renderer_Z_vftable_82@D3D_Renderer_Z@@UAEXH@Z");
    virtual void Renderer_Z_vftable_82(int) override;
    ADDRESSSYMBOL(0x008500E0, "?Renderer_Z_vftable_83@D3D_Renderer_Z@@UAEXHHH@Z");
    virtual void Renderer_Z_vftable_83(int, int, int) override;
    ADDRESSSYMBOL(0x00850D30, "?Renderer_Z_vftable_84@D3D_Renderer_Z@@UAEXHHHH@Z");
    virtual void Renderer_Z_vftable_84(int, int, int, int) override;
    ADDRESSSYMBOL(0x008501E0, "?Renderer_Z_vftable_85@D3D_Renderer_Z@@UAEXHHH@Z");
    virtual void Renderer_Z_vftable_85(int, int, int) override;
    ADDRESSSYMBOL(0x00850260, "?Renderer_Z_vftable_86@D3D_Renderer_Z@@UAEXHHH@Z");
    virtual void Renderer_Z_vftable_86(int, int, int) override;
    ADDRESSSYMBOL(0x0084F630, "?Renderer_Z_vftable_87@D3D_Renderer_Z@@UAEPAXXZ");
    virtual void *Renderer_Z_vftable_87() override;
    ADDRESSSYMBOL(0x00851250, "?Renderer_Z_vftable_88@D3D_Renderer_Z@@UAEXHHHH@Z");
    virtual void Renderer_Z_vftable_88(int, int, int, int) override;
    ADDRESSSYMBOL(0x00851400, "?Renderer_Z_vftable_89@D3D_Renderer_Z@@UAEXHHHHH@Z");
    virtual void Renderer_Z_vftable_89(int, int, int, int, int) override;
    ADDRESSSYMBOL(0x008515E0, "?Renderer_Z_vftable_91@D3D_Renderer_Z@@UAEXHHHH@Z");
    virtual void Renderer_Z_vftable_91(int, int, int, int) override;
    ADDRESSSYMBOL(0x008517C0, "?Renderer_Z_vftable_92@D3D_Renderer_Z@@UAEHHHHHH@Z");
    virtual int Renderer_Z_vftable_92(int, int, int, int, int) override;
    ADDRESSSYMBOL(0x00851860, "?Renderer_Z_vftable_93@D3D_Renderer_Z@@UAEXHH@Z");
    virtual void Renderer_Z_vftable_93(int, int) override;
    ADDRESSSYMBOL(0x008508D0, "?Renderer_Z_vftable_94@D3D_Renderer_Z@@UAEXHHHHHH@Z");
    virtual void Renderer_Z_vftable_94(int, int, int, int, int, int) override;
    ADDRESSSYMBOL(0x008505F0, "?Renderer_Z_vftable_95@D3D_Renderer_Z@@UAEXHHHHHHHH@Z");
    virtual void Renderer_Z_vftable_95(int, int, int, int, int, int, int, int) override;
    ADDRESSSYMBOL(0x00850B20, "?Renderer_Z_vftable_96@D3D_Renderer_Z@@UAEXHHHHH@Z");
    virtual void Renderer_Z_vftable_96(int, int, int, int, int) override;
    ADDRESSSYMBOL(0x00850F70, "?Renderer_Z_vftable_97@D3D_Renderer_Z@@UAEXHHHH@Z");
    virtual void Renderer_Z_vftable_97(int, int, int, int) override;
    ADDRESSSYMBOL(0x00854230, "?Renderer_Z_vftable_98@D3D_Renderer_Z@@UAEXHHHHHH@Z");
    virtual void Renderer_Z_vftable_98(int, int, int, int, int, int) override;
    ADDRESSVF(0x00839BC0, D3D_Renderer_Z, Renderer_Z_vftable_99);
    virtual void Renderer_Z_vftable_99() override;
    ADDRESSVF(0x00839BB0, D3D_Renderer_Z, Renderer_Z_vftable_100);
    virtual void Renderer_Z_vftable_100() override;
    ADDRESSSYMBOL(0x00854600, "?Renderer_Z_vftable_101@D3D_Renderer_Z@@UAEDHHHHH@Z");
    virtual char Renderer_Z_vftable_101(int, int, int, int, int) override;
    ADDRESSSYMBOL(0x00843B80, "?Renderer_Z_vftable_102@D3D_Renderer_Z@@UAEXH@Z");
    virtual void Renderer_Z_vftable_102(int) override;
    ADDRESSVF(0x00854A60, D3D_Renderer_Z, Renderer_Z_vftable_103);
    virtual void Renderer_Z_vftable_103() override;
    ADDRESSVF(0x00854B10, D3D_Renderer_Z, Renderer_Z_vftable_104);
    virtual void Renderer_Z_vftable_104() override;
    virtual void Renderer_Z_vftable_105() override;
    ADDRESSSYMBOL(0x008437A0, "?Renderer_Z_vftable_106@D3D_Renderer_Z@@UAEXXZ");
    virtual void Renderer_Z_vftable_106() override;
    virtual int Renderer_Z_vftable_107(int, int, int) override;
    virtual void Renderer_Z_vftable_108(int, int, int, int) override;
    ADDRESSVF(0x00836840, D3D_Renderer_Z, D3D_Renderer_Z_vftable_109);
    virtual void D3D_Renderer_Z_vftable_109();
    ADDRESSVF(0x0086E110, D3D_Renderer_Z, D3D_Renderer_Z_vftable_110);
    virtual void D3D_Renderer_Z_vftable_110();
    ADDRESSVF(0x0086E190, D3D_Renderer_Z, D3D_Renderer_Z_vftable_111);
    virtual void D3D_Renderer_Z_vftable_111();
    ADDRESSVF(0x0086E0D0, D3D_Renderer_Z, D3D_Renderer_Z_vftable_112);
    virtual void D3D_Renderer_Z_vftable_112();
    ADDRESSVF(0x00839BA0, D3D_Renderer_Z, D3D_Renderer_Z_vftable_113);
    virtual void D3D_Renderer_Z_vftable_113();
    ADDRESSVF(0x00839B90, D3D_Renderer_Z, D3D_Renderer_Z_vftable_114);
    virtual void D3D_Renderer_Z_vftable_114();
    IDirect3D9 *pD3D;
    IDirect3DDevice9 *pD3DDevice;
    HWND hDestWindowOverride;
    PAD(1472);
    D3DFORMAT field_37CC;
    PAD(232720);
    char field_3C4E0[26];
    PAD(1760);
    char field_3CBDA;
    PAD(1);
    char field_3CBDC;
    char field_3CBDD;
    PAD(7);
    char field_3CBE5;
    PAD(42);
    int field_3CC10;
    int field_3CC14;
    int field_3CC18;
    PAD(8020);
    int field_3EB70;
    PAD(176);
};
PACK_POP

#endif // _D3DTNL_RENDERER_Z_H_
