#pragma once

#ifndef _RENDERER_Z_H_
#define _RENDERER_Z_H_

#include "Types_Z.h"

PACK_PUSH
ADDRESSVFTABLE(0x009C6514, Renderer_Z);
class __declspec(dllexport) Renderer_Z
{
public:
    ADDRESSVF(0x00650BA0, Renderer_Z, Renderer_Z_vftable_0);
    virtual void Renderer_Z_vftable_0();
    ADDRESSVF(0x00651470, Renderer_Z, Renderer_Z_vftable_1);
    virtual void Renderer_Z_vftable_1();
    virtual void Renderer_Z_vftable_2();
    virtual void Renderer_Z_vftable_3();
    virtual void Renderer_Z_vftable_4();
    virtual void Renderer_Z_vftable_5();
    ADDRESSVF(0x00652900, Renderer_Z, Renderer_Z_vftable_6);
    virtual void Renderer_Z_vftable_6();
    ADDRESSVF(0x00651810, Renderer_Z, Renderer_Z_vftable_7);
    virtual void Renderer_Z_vftable_7();
    ADDRESSVF(0x00652870, Renderer_Z, Renderer_Z_vftable_8);
    virtual void Renderer_Z_vftable_8();
    virtual void Renderer_Z_vftable_9();
    virtual void Renderer_Z_vftable_10(int);
    virtual void Renderer_Z_vftable_11();
    ADDRESSVF(0x00773530, Renderer_Z, Renderer_Z_vftable_12);
    virtual void Renderer_Z_vftable_12();
    virtual void Renderer_Z_vftable_13(int);
    virtual void Renderer_Z_vftable_14(int);
    ADDRESSVF(0x00651560, Renderer_Z, Renderer_Z_vftable_15);
    virtual void Renderer_Z_vftable_15();
    ADDRESSVF(0x00658C80, Renderer_Z, Renderer_Z_vftable_16);
    virtual void Renderer_Z_vftable_16();
    virtual char Renderer_Z_vftable_17(int, int, int, int, int, int);
    virtual void Renderer_Z_vftable_18(int, int, int);
    virtual void Renderer_Z_vftable_19(int);
    virtual void Renderer_Z_vftable_20(int);
    virtual void Renderer_Z_vftable_21(int);
    ADDRESSVF(0x00658C00, Renderer_Z, Renderer_Z_vftable_22);
    virtual void Renderer_Z_vftable_22();
    ADDRESSVF(0x00658BF0, Renderer_Z, Renderer_Z_vftable_23);
    virtual void Renderer_Z_vftable_23();
    ADDRESSVF(0x00658BE0, Renderer_Z, Renderer_Z_vftable_24);
    virtual void Renderer_Z_vftable_24();
    ADDRESSVF(0x00658BD0, Renderer_Z, Renderer_Z_vftable_25);
    virtual void Renderer_Z_vftable_25();
    virtual void *Renderer_Z_vftable_26();
    virtual void Renderer_Z_vftable_27(int, int);
    ADDRESSVF(0x00658F60, Renderer_Z, Renderer_Z_vftable_28);
    virtual void Renderer_Z_vftable_28();
    ADDRESSVF(0x00658BA0, Renderer_Z, Renderer_Z_vftable_29);
    virtual void Renderer_Z_vftable_29();
    virtual void Renderer_Z_vftable_30();
    virtual int Renderer_Z_vftable_31();
    virtual void Renderer_Z_vftable_32(int, int, int, int, int, int, int, int);
    virtual void Renderer_Z_vftable_33(int);
    virtual void Renderer_Z_vftable_34(int);
    virtual void Renderer_Z_vftable_35(int, int);
    virtual void Renderer_Z_vftable_36(int, int);
    virtual void Renderer_Z_vftable_37(int);
    virtual void Renderer_Z_vftable_38(int);
    virtual void Renderer_Z_vftable_39(int);
    ADDRESSVF(0x00658AF0, Renderer_Z, Renderer_Z_vftable_40);
    virtual void Renderer_Z_vftable_40();
    virtual void Renderer_Z_vftable_41(int, int);
    virtual void Renderer_Z_vftable_42(int);
    ADDRESSVF(0x00658AC0, Renderer_Z, Renderer_Z_vftable_43);
    virtual void Renderer_Z_vftable_43();
    ADDRESSVF(0x00658AA0, Renderer_Z, Renderer_Z_vftable_44);
    virtual void Renderer_Z_vftable_44();
    ADDRESSVF(0x00658A50, Renderer_Z, Renderer_Z_vftable_45);
    virtual void Renderer_Z_vftable_45();
    virtual int Renderer_Z_vftable_46(int);
    virtual int Renderer_Z_vftable_47(int);
    virtual int Renderer_Z_vftable_48(int);
    virtual int Renderer_Z_vftable_49(int);
    virtual int Renderer_Z_vftable_50(int);
    virtual int Renderer_Z_vftable_51(int);
    virtual int Renderer_Z_vftable_52();
    virtual int Renderer_Z_vftable_53();
    virtual int Renderer_Z_vftable_54();
    virtual int Renderer_Z_vftable_55();
    virtual int Renderer_Z_vftable_56();
    virtual int Renderer_Z_vftable_57();
    virtual int Renderer_Z_vftable_58();
    virtual int Renderer_Z_vftable_59();
    ADDRESSVF(0x00652B00, Renderer_Z, Renderer_Z_vftable_60);
    virtual void Renderer_Z_vftable_60();
    virtual void Renderer_Z_vftable_61(int);
    ADDRESSVF(0x00658940, Renderer_Z, Renderer_Z_vftable_62);
    virtual void Renderer_Z_vftable_62();
    ADDRESSVF(0x00658930, Renderer_Z, Renderer_Z_vftable_63);
    virtual void Renderer_Z_vftable_63();
    ADDRESSVF(0x007731B0, Renderer_Z, Renderer_Z_vftable_64);
    virtual void Renderer_Z_vftable_64();
    ADDRESSVF(0x00773200, Renderer_Z, Renderer_Z_vftable_65);
    virtual void Renderer_Z_vftable_65();
    ADDRESSVF(0x00773250, Renderer_Z, Renderer_Z_vftable_66);
    virtual void Renderer_Z_vftable_66();
    ADDRESSVF(0x007732B0, Renderer_Z, Renderer_Z_vftable_67);
    virtual void Renderer_Z_vftable_67();
    ADDRESSVF(0x00658920, Renderer_Z, Renderer_Z_vftable_68);
    virtual void Renderer_Z_vftable_68();
    ADDRESSVF(0x00652AD0, Renderer_Z, Renderer_Z_vftable_69);
    virtual void Renderer_Z_vftable_69();
    virtual char Renderer_Z_vftable_70(int);
    ADDRESSVF(0x00657200, Renderer_Z, Renderer_Z_vftable_71);
    virtual void Renderer_Z_vftable_71();
    ADDRESSVF(0x00657230, Renderer_Z, Renderer_Z_vftable_72);
    virtual void Renderer_Z_vftable_72();
    ADDRESSVF(0x006588C0, Renderer_Z, Renderer_Z_vftable_73);
    virtual void Renderer_Z_vftable_73();
    ADDRESSVF(0x00658840, Renderer_Z, Renderer_Z_vftable_74);
    virtual void Renderer_Z_vftable_74();
    virtual int Renderer_Z_vftable_75();
    ADDRESSVF(0x00658820, Renderer_Z, Renderer_Z_vftable_76);
    virtual void Renderer_Z_vftable_76();
    ADDRESSVF(0x00650F80, Renderer_Z, Renderer_Z_vftable_77);
    virtual void Renderer_Z_vftable_77();
    ADDRESSVF(0x006587F0, Renderer_Z, Renderer_Z_vftable_78);
    virtual void Renderer_Z_vftable_78();
    ADDRESSVF(0x00657260, Renderer_Z, Renderer_Z_vftable_79);
    virtual void Renderer_Z_vftable_79();
    ADDRESSVF(0x006573F0, Renderer_Z, Renderer_Z_vftable_80);
    virtual void Renderer_Z_vftable_80();
    virtual int Renderer_Z_vftable_81(int, int, int, int);
    virtual void Renderer_Z_vftable_82(int);
    virtual void Renderer_Z_vftable_83(int, int, int);
    virtual void Renderer_Z_vftable_84(int, int, int, int);
    virtual void Renderer_Z_vftable_85(int, int, int);
    virtual void Renderer_Z_vftable_86(int, int, int);
    virtual void *Renderer_Z_vftable_87();
    virtual void Renderer_Z_vftable_88(int, int, int, int);
    virtual void Renderer_Z_vftable_89(int, int, int, int, int);
    virtual void Renderer_Z_vftable_90(int);
    virtual void Renderer_Z_vftable_91(int, int, int, int);
    virtual int Renderer_Z_vftable_92(int, int, int, int, int);
    virtual void Renderer_Z_vftable_93(int, int);
    virtual void Renderer_Z_vftable_94(int, int, int, int, int, int);
    virtual void Renderer_Z_vftable_95(int, int, int, int, int, int, int, int);
    virtual void Renderer_Z_vftable_96(int, int, int, int, int);
    virtual void Renderer_Z_vftable_97(int, int, int, int);
    virtual void Renderer_Z_vftable_98(int, int, int, int, int, int);
    ADDRESSVF(0x006586B0, Renderer_Z, Renderer_Z_vftable_99);
    virtual void Renderer_Z_vftable_99();
    ADDRESSVF(0x00658690, Renderer_Z, Renderer_Z_vftable_100);
    virtual void Renderer_Z_vftable_100();
    virtual char Renderer_Z_vftable_101(int, int, int, int, int);
    virtual void Renderer_Z_vftable_102(int);
    ADDRESSVF(0x00658650, Renderer_Z, Renderer_Z_vftable_103);
    virtual void Renderer_Z_vftable_103();
    ADDRESSVF(0x00658640, Renderer_Z, Renderer_Z_vftable_104);
    virtual void Renderer_Z_vftable_104();
    ADDRESSVF(0x00651770, Renderer_Z, Renderer_Z_vftable_105);
    virtual void Renderer_Z_vftable_105();
    virtual void Renderer_Z_vftable_106();
    virtual int Renderer_Z_vftable_107(int, int, int);
    virtual void Renderer_Z_vftable_108(int, int, int, int);
    int field_4;
    PAD(3336);
    int field_D10;
    int field_D14;
    PAD(280);
    char field_E30;
    PAD(79);
    char field_E80[176];
    PAD(408);
    char field_10C8;
    PAD(67);
    U32 field_110C;
    PAD(8432);
};
PACK_POP

#endif // _RENDERER_Z_H_
